name: CI/CD - Docker & Render

on:
  push:
    branches:
      - main  # Se ejecutará cuando hagas push a la rama main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      # 1. Login en Docker Hub
      - name: Login en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 2. Construir la imagen Docker
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ciclo-devops:latest .

      # 3. Push a Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/ciclo-devops:latest

      # 4. Desplegar en Render usando API
      - name: Deploy to Render
        run: |
          curl -X POST \
          -H "Accept: application/json" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -d '' \
          https://api.render.com/v1/services/srv-d29q8aggjchc73cpo760/deploys
